name: Main Workflow

on:
  push:
    branches: [main, master, develop]
    tags:
      - 'v*'
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  setup-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (Linux or Mac)
        run: |
          if command -v brew &>/dev/null; then
            brew install pkg-config cairo pango libpng jpeg giflib librsvg
          elif command -v apt-get &>/dev/null; then
            sudo apt-get update
            sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          fi
  ci-cd:
    uses: ./.github/workflows/reusable-mcp-workflow.yml
    with:
      package-name: '@lepion/mcp-server-mermaid'
      node-version: '18.x'
      run-tests: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
